site_name: Plotter Art

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Plotter Art Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
